language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: AXblaSBh17UGFU7Z1BQG8sGia+HH+PJlTcv+GZgvNUSMkHN96AW7FL5Z7a1hourk970shFEFMHbjYAaMlbgv5W0sspZp6nytBiq42/nSxgUfGwDKRMqwzY0Eu0D3xMTI8Vagb24VBaS0MhmG10Y9QLfUl2fJGXgdV8Jjg9WIT2RliKlm74K1WWCry66KxSJ8VqybNZz/lFdV/M89dKwAa5FOvsgQmirEQmDVj1J06IOil0Eih2hMLI1/po44zdL7H6CZ35sWNRhJK5Ii+JhtdLdQGu4RDaRt/R8noA9uBA2sHHTr9qnqD7wXfdo8Gnm5vbAqmV/j6DKTVXpsibgcBIk6I1LsJkA/47sqQatbESd85kzQ4ism/6DfXiJ8Z60BukJokdykDgWCKfpnV78eWHJWZfRV5Bq4xJ9fukZ3O/lVc+hZIoyAWgUqOtrwHP7JxCbV4BR3+9+5PSvd1rJPxHt5f8d2rlS4m+o8xlz1wivVD/DSdOyib4O/+A15yaoR0aeFT2tShR5WfnnrtWXmwO1cc1gwBSLapsbcGduD8GSrPwh27w1YzEi7pMByPmaoFec2R+CGb0eFVyZIehwxSx4u7sHSRbpSSnviRYHEQS/Qz8SFKdc125V4wsopOo4Kh7NXIdknbgQZ906jEjLrZ3iS4NCRDUWJ38wAS35pS90=
  app: lpa1
  on:
    repo: balmajoe/projet
