language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: IMEKSE4xgQdgzVr0hNBy38cF+2829mD8e5Gh6MsRw+p3vBkfR1Gh3uNGlMINOe/NZfc4GY0gCslrt1q7Z4giAJ8RDn1YTv5wkS610VnL6huvdJnzPNx2EmmG5cL/TghwDU5OtCabxdDAetcyWEaoNkqD0I8J7Gu8CEPpwhqybMyVMovBMQsalh5NYQM27iPmFOMj9Lxwpx8ptdhyvlzH7VlgBTpsRCIToEXyawezWY1hTf77XC2HRAu7mW2XHwOYzini4RPT3JAkE4pxh8NFUUUqDkDnPStBkXulZXlxZPacHXoclJ6qQUU1/bn0Zy2OUwkTLWutmo6dqpT7SSLGZE0AG3UbbuPIfPTpUH0KVCROqwrdYn0NuXGX9lic6pu45yJPtIg+1UyJ9AAo+usxJywFt6XzLf/vqQ2c5fJ/UjT/GHkIpALBMzAyqlKJ7jLQjUedIh3cxmOuB8bWyFVUzGV8drHlMgFfcP3o2uNR8q+v7b7e8Ic9h0wbp/BudNpXxO/GwcHF3AJXVhx6nPbb7cvkvgSRJBNBO02aeTbtBXf0mJnOawovelZbn64+dLBqg+OkHtyu5lfRVe9MG70k3DadcP+9yxZpPGW5778qbNLCStIu5BhFZpHE4Fj04Tjs767g3/xb2gDH4Mg2uKXLa+BEgtC381vunt5XecoJEhA=
  app: lp12
  on:
    repo: balmajoe/projet
