language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: lHspvtoiqeNqmCpWwOCqpYj0UC/pJQ4senXI1b/7eE+wj/VzfJCCubvvPkXNyjvN57avGNA6r9kD+Or4qjQ8RGV2OWd5sK/M0aksZP3oKTHQyZL1j248bKFb0fFVz6OuYcGzEYNfvsCzn/hob+dJupAtxoC56XwJkuo0RhwZHcRtTct9eqMIfcHl9Puz1yQjrdxY8sv0M7TIcMPZ+LGkX18nWAuqD+3HgatzE8BNdcEiJjajbEsC7Op/Uoqf9sZVZ90RzCsIPXd8bsaTuB/AR/qevTTeHVt7qEqyAVa/Igag0J9nVmsUqiiYXIX51HqE1DrzfQR6/cj/mD2s5O6N7s+agJi75AGjLo9N6NmtBVGZoJerHiCFqw7aagOTV4+liXqMI8otJ5y82+V414T4Hv5AFNEa+Ji3d0Zl9J282CcD4zkac1CYIB/+XyqoHiq67G3bkulbyppu/YIYZnTpTlNhsZkIExDaWNk31DboFku3riUF6BpqLcWukvl+CN3EOW4GwOxjdGJM+Nw8lvg6tLGEAFq1QwBIAgLBmVxiq1OH6A8YG5m2DynfVL/lFwYs/DYIMhdMXYHORLNCpzvr5m8cJr6VBiKv0znCW3F+CTsP1XyIEkxv6ZZz7OPsM9pn7CVYAQkiGzVlap5gWB57HOEvbDvPg2PlZQL7hgGgHzo=
  app: lpa1
  on:
    repo: balmajoe/projet
