language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: W/U4JbBfdcmEkoDJaVER0fBmCP1nDg2RnAOSJGC/3embgvnbKe1dA8JG6o86vWze9iNDDAyKWNYZEHBcQdqKME4r7GS5jn9CvYqBnlv+xcN52k/MR6h1EkL9RhOR6FnbMX5biuwwFGVaUfuawqvcJiFrIveFGaOXnqDnlf6M7ly5I8voV3mLg89cQFhguu5hEysX+ebJy2UNtuqb40Nhs9TEDRzY7XcMRZ3EON0/3bxNoqnZ48fa3AsgbxggtzkhTyVLpq24bLn1j4DDnyo3EuNu+c1aTrrGnWXRgPyc5dHjk5zHyXXuz4MKXuG21csOxCw6vnEzdw0rJoev/CgzTgXdMOOSINQsBXMDkLqn574xt+xyULgGx4SierHy/QmYA8r3J/CUdzHao2VHXQ6uC93PXWJAXsng0WZ/LVxg6zufurwphFXGjYaeeTIRBNKMWKshjVrjoEgUsSTCZsh3Y5KHZfXrOZCgxTt7qH57vlTkbXM2Sl55b1tk0852Jp6HcD8JvVztyJrCrRN6NYy+7DK6o9VWVP5/CeEPnQybBQzdtMjk5a4sp7xtxsHvlatCOP8PwbAljnJ4fSSIw9u5JAfjD99XKMkMr3AhorF35OppnmG6GQcmaza+UYoKgC1hhwoY+LXs2f4IUcJj0Ldh6CCraT+ezG3ECtn0oHgd0Ds=
  app: lpa1
