language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: dENztrRYT1rtfYmtSucklKWRq4xkxHO/DxAgjWJ0sVAcRp7Fn6WPYD650julFIn2nX+w8DlVYd7jXTpGcnoDOw1ay3kkQQb/hRu9bZliJC4xJd9+F1VcdlbZ0iGJlfz5aTxn03K0YYiF/cmTpFTH39m1G7g7322FY7AoFGV6PdnPJMqIgtBQP5dEW9zMIk0CoLmmAgcGmJesaWJaUhIcpZH3102PJDUl6xOfRx0A7tqI59+5RvekUTH8Dx0dvucICNlv3/llHnwdi+qkT8lx9GqUmN5M9WPBrrmZd+vZb54o9m+Q4zzN7DyxhoPtR4faCUZGqq2Z1wjt2xP1sCQ1EJ2PVwENepcReIuyIoHhI1PVkWW7yySws9nKZ68qM/xuVsAMdXpPeHrN95PyuEAenT0Hbjaza0NBkgTtW0WtlpHG4RNQflwoD1KUKKc7R5MU8ozcaCuAZT+5GE9bQ/3ItshxV674AEifAg+d1g9UJIG9W9UTdkJIZFd8Xs/BD9xRzjX0QRKLTWRjzUWox8Xj9+KF89DBCLG/VyPaMk2eH1hqoeWqobIc055DOgsWfwPQmkjcVyV0CQ7GOAFe/DL92SNvCZPKdOOp9hpuok1x0Nqqx3K5tytLUH+wwULdQ7sSe+EgiSsENnh3ZkIEMsSTACIcdQECL0VRwV2sps46QVU=
  app: lpa1
  on:
    repo: balmajoe/projet
