language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: 0ACBkWiPLZAekUH3/hjXlYbn2cjFH7tiX2Naeau/htdGEevFkz0X6HEYH061DLw6LAzrD8FPqz9hVxyoyXrqfe6GHSTo8T29uhkjC1YaxmnO1mYjgw8s/8Os51/ARUL9wFRzRFGJGfAeFG1ObNxoAXFtNRKCZiTY4AcYt50cGB2b5oFdb3jhRZtiOwGRBXd0TiUVrrLxBT1bxOv/mjPKyF81AF8hA4n6AI98U/uaCqAMsulY7SolUbonMMTYT8af6wEMoLYjhqAiuCl0vgIgF05ymWUllQYXD4ug+j93PHowClKldEBS3f9k/MvQwR4vrxB6772nviQI9i6qcS8XmL27AUkAgKVeg6UAOPqtXurjXjQPsdyURaGV15Ol9QCZ2fSC7/X5ZvnXaakcxeWeTp7C7UqNfnD6iRmiuQzzi3OajU7uyybyKv1/pryEajVP6rIJaBjkXjCBvBlR3cbDpObLoVdRz/cLRa9lDpW9jv3UtoLGON1HILyBmDJs1ifCt6W6DTsxCksmZnxlA6UCR85CFMUB8dKReKP8ZOahFVyWka5vttv/VoZ0ZMW4VQ9k8SotjHm/evVNJZ0HPrYaG3OeU1wDC2QhHeXj21JceBnEuCSredcP/nAtZdW7/1ZF3gDpADHKRgXarCUvatY/uYmlffSGiU511/NB8Bsqo1w=
  app: lpa1
  on:
    repo: balmajoe/projet
