language: ruby
rvm:
- 2.2
deploy:
  provider: heroku
  api_key:
    secure: hSKetdCgjNagun0JxWB9K4wmIZAnXy2NOCmGBlf7SzqhmwL5sXpEjchy9nNPQMRyJheJdQjy/i4lAvE/qwWzuEhYGiXUaylXn+zIt6Ydmhtqv/PN741B4nbdlw12g46/sFm+4v65qmc3YCPb/TL2zSftqEyhV0dT+57E0dMR3Ejyzt+MO1OUDuTrZyL0k9KGS44Etp6IDRaukqjzj1+sooF2JOIsCGMFDZ5lI37+U5jkdD/+CjH6JYrkdaeaJb+2/VODYlv08qPO083/9qdYAtG9vcC8nnKsivbfBKNIQXGZDP4+6dmBNa7rqvLwz9ALDI+DE7uokkieUgfHYPQo1am33hGj3ixGXjul3El/EyzBypOYQmYk/ZyCBuP6TvPV1gGSosFhS/KdGDBSumkMj/cxh/K2S+wGz0INAibdNRjwjIzdFe3+Hsfabs3qfJq9/sVWZUXVL3jkxu8gMzsJLBatDGZMCt/fThNQI4CDdLXzkheSH/XBXwgmguxp+v8txgU+wGNFU0gGpKmn5IPD8A2SUbS/ooV/FvKu+Fj3eMzvXxALlomTggxZm6/1poenOqVqgssx0wO5IlAH5YNXULy8Lwk/S4W4iWbiZdd75Q0iZbkDVma+rQTNdUJS51MJzDlLgmbUrod3/lZRKpvYmO8SsnFjJPDYWGyoo5mWRng=
  app: lp12
  on:
    repo: balmajoe/projet
